<?php

  // include base peer class
  require_once 'import/classes/om/BaseClientQuotationItemPeer.php';

  // include object class
  include_once 'import/classes/ClientQuotationItem.php';


/**
 * Skeleton subclass for performing query and update operations on the 'import_clientQuotationItem' table.
 *
 * Elemento de Cotizacion Cliente
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:02:11 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class ClientQuotationItemPeer extends BaseClientQuotationItemPeer {

  /**
  * Crea un client quotation item nuevo sin persistirlo en la base de datos
  *
  * @param array $params Array asociativo con los atributos del objeto
  * @return ClientQuotationItem instance
  */
  function createInstance($params) {

     $clientquotationItemObj = new ClientQuotationItem();
     foreach ($params as $key => $value) {
       $setMethod = "set".$key;
       if ( method_exists($clientquotationItemObj,$setMethod) ) {          
         if (!empty($value))
           $clientquotationItemObj->$setMethod($value);
         else
           $clientquotationItemObj->$setMethod(null);
       }
     }
	 return $clientquotationItemObj;
	
  }
  

  /**
  * Crea un client quotation item nuevo y lo persiste.
  *
  * @param array $params Array asociativo con los atributos del objeto
  * @return ClientQuotationItem instance
  */  
  function create($params) {
    try {
      $clientquotationItemObj = ClientQuotationItemPeer::createInstance($params);
      $clientquotationItemObj->save();
      return $clientquotationItemObj;
    } catch (Exception $exp) {
      return false;
    }         
  }

  /**
  * Actualiza un client quotation item nuevo.
  *
  * @param array $params Array asociativo con los atributos del objeto
  * @return ClientQuotation creado, false sino
  */  
  function update($params) {
    try {
      $clientquotationItemObj = ClientQuotationItemPeer::get($params['id']);
      foreach ($params as $key => $value) {
        $setMethod = "set".$key;
        if ( method_exists($clientquotationItemObj,$setMethod) ) {          
          if (!empty($value))
            $clientquotationItemObj->$setMethod($value);
          else
            $clientquotationItemObj->$setMethod(null);
        }
      }

	  if ($params['price'] != '') {
	  	//se ha fijado un precio de un item
	    $clientQuotation = $clientquotationItemObj->getClientQuotation();
		if ($clientQuotation->getStatus() == ClientQuotation::STATUS_WAITING_FOR_PRICING) {
			$clientQuotation->setStatus(ClientQuotation::STATUS_PARTIALLY_QUOTED);
			$clientQuotation->save();
			$clientQuotation->saveCurrentStatusOnHistory();			
		}
	  }
		
      $clientquotationItemObj->save();
      return $clientquotationItemObj;
    } catch (Exception $exp) {
      return false;
    }         
  }

  /**
  * Obtiene la informacion de un client quotation item.
  *
  * @param int $id id del clientquotation
  * @return array Informacion del clientquotation
  */
  function get($id) {
		$clientquotationItemObj = ClientQuotationItemPeer::retrieveByPK($id);
    return $clientquotationItemObj;
  }



} // ClientQuotationItemPeer
