<?php

require_once 'import/classes/om/BaseClientQuotationItem.php';
require_once('SupplierQuotationItemPeer.php');


/**
 * Skeleton subclass for representing a row from the 'import_clientQuotationItem' table.
 *
 * Elemento de Cotizacion Cliente
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:02:11 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class ClientQuotationItem extends BaseClientQuotationItem {
	
	/**
	 * Obtiene el elemento de cotizacion del proveedor
	 * @return SupplierQuotationItem instancia de Supplier QuotationItem o vacio en caso de que aun no se haya asignado
	 */
	public function getSupplierQuotationItem() {
		
		$criteria = new Criteria();
		$criteria->add(SupplierQuotationItemPeer::CLIENTQUOTATIONITEMID,$this->getId());
		$result = SupplierQuotationItemPeer::doSelect($criteria);
		return $result[0];
		
	}
	
	/**
	 * Indica si este elemento ya ha sido designado para cotizacion.
	 * @return boolean
	 */
	public function hasASupplierQuotationRelated() {
		$supplierQuotationItem = $this->getSupplierQuotationItem();
		return (!empty($supplierQuotationItem));
	}
	
	/**
	 * Obtiene las ultimas cotizaciones realizadas al cliente sobre este item
	 * que hayan tenido fijado un precio
	 */
	public function getLastClientQuotationItemsRelated() {
		$criteria = new Criteria();
		$criteria->add(ClientQuotationItemPeer::PRODUCTID,$this->getProductId());
		$criteria->add(ClientQuotationItemPeer::ID,$this->getId(),Criteria::NOT_EQUAL);
		$criteria->add(ClientQuotationItemPeer::PRICE,'',Criteria::NOT_EQUAL);
		$result = SupplierQuotationItemPeer::doSelect($criteria);
		return $result;
	}

} // ClientQuotationItem
