<?php

  // include base peer class
  require_once 'import/classes/om/BaseClientQuotationItemPeer.php';

  // include object class
  include_once 'import/classes/ClientQuotationItem.php';


/**
 * Skeleton subclass for performing query and update operations on the 'import_clientQuotationItem' table.
 *
 * Elemento de Cotizacion Cliente
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:02:11 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class ClientQuotationItemPeer extends BaseClientQuotationItemPeer {

  /**
  * Crea un client quotation item nuevo.
  *
  * @param array $params Array asociativo con los atributos del objeto
  * @return ClientQuotation creado, false sino
  */  
  function create($params) {
    try {
      $clientquotationItemObj = new ClientQuotationItem();
      foreach ($params as $key => $value) {
        $setMethod = "set".$key;
        if ( method_exists($clientquotationItemObj,$setMethod) ) {          
          if (!empty($value))
            $clientquotationItemObj->$setMethod($value);
          else
            $clientquotationItemObj->$setMethod(null);
        }
      }
      $clientquotationItemObj->save();
      return $clientquotationItemObj;
    } catch (Exception $exp) {
      return false;
    }         
  }  


} // ClientQuotationItemPeer
