<?php

require_once 'import/classes/om/BaseProduct.php';


/**
 * Skeleton subclass for representing a row from the 'product' table.
 *
 * Productos
 *
 * This class was autogenerated by Propel on:
 *
 * 12/05/07 13:19:20
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class Product extends BaseProduct {

	/**
	 * Redefinimos delete para evitar que se haga borrado real cuando 
	 * se elimina desde el objeto. sin usar la clase peer.
	 */
	function delete (PropelPDO $con = null) {
		$this->setactive('0');
		$this->save();
	}
	
	public function getProductSupplier() {
		
		require_once('ProductSupplierPeer.php');
		
		$criteria = new Criteria();
		$criteria->add(ProductSupplierPeer::PRODUCTID,$this->getId());
		$result = ProductSupplierPeer::doSelect($criteria);
		return $result[0];
		
	}
	
	public function getSupplier() {

		$relationship = $this->getProductSupplier();

		if (empty($relationship)) {
			return false;
		}

		$supplier = $relationship->getSupplier();
				
		return $supplier;
	}
	
	public function getSupplierId() {
		$supplier = $this->getSupplier();
		
		if (empty($supplier)) {
			return false;
		}
		
		return $supplier->getId();
	}
	
	public function getSupplierProductCode() {

		$relationship = $this->getProductSupplier();

		if (empty($relationship)) {
			return false;
		}

		$code = $relationship->getCode();
	
		return $code;
		
	}

} // Product
