<?php

require_once 'import/classes/SupplierPurchaseOrderItem.php';
require_once 'import/classes/map/SupplierPurchaseOrderItemMapBuilder.php';
require_once 'import/classes/SupplierPurchaseOrderItemPeer.php';
require_once 'import/classes/map/SupplierPurchaseOrderHistoryMapBuilder.php';
require_once 'import/classes/SupplierPurchaseOrderHistory.php';
require_once 'import/classes/SupplierPurchaseOrderHistoryPeer.php';
require_once 'import/classes/om/BaseSupplierPurchaseOrder.php';


/**
 * Skeleton subclass for representing a row from the 'import_supplierPurchaseOrder' table.
 *
 * Orden de Pedido a Proveedor
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:24:15 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class SupplierPurchaseOrder extends BaseSupplierPurchaseOrder {
	
	const STATUS_FABRICATION_NON_INITIATED = 1;
	
	//nombre de los estados para los clientes
	private $statusNames = array(
								SupplierPurchaseOrder::STATUS_FABRICATION_NON_INITIATED => 'Fabrication Non Initiated',
							);
	
	/**
	 * Saves the current status of the instance in his history
	 * @return boolean
	 */
	public function saveCurrentStatusOnHistory() {
		
		require_once('SupplierPurchaseOrderHistory.php');
		
		try {

			$supplierPurchaseOrderHistory = new SupplierPurchaseOrderHistory();
			$supplierPurchaseOrderHistory->setSupplierPurchaseOrder($this);
			$supplierPurchaseOrderHistory->setStatus($this->getStatus());
			$supplierPurchaseOrderHistory->setCreatedAt(time());
			$supplierPurchaseOrderHistory->save();
			
		} catch (Exception $e) {
			return false;
		}
		
		return true;
	}

	/**
	 * Devuelve un array con los nombres de los distintos mensajes de status para el adminstrador
	 * @return array
	 */
	public function getStatusNames() {
		return $this->statusNames;
	}	


	/**
	 * Devuelve el nombre del status actual de la cotizacion para un administrador
	 * @return string
	 */
	public function getStatusName() {
		return $this->statusNames[$this->getStatus()];
	}
		

} // SupplierPurchaseOrder
