<?php

require_once 'import/classes/om/BaseSupplierQuotationItem.php';


/**
 * Skeleton subclass for representing a row from the 'import_supplierQuotationItem' table.
 *
 * Elemento de Cotizacion de Proveedor
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:02:11 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class SupplierQuotationItem extends BaseSupplierQuotationItem {
	
	const PACKAGE_BY_UNIT = 1;
	const PACKAGE_BY_CARTON = 2;
	
	/**
	 * Calcula el volumen en m3 segun la informacion ingresada en la cotizacion sobre la unidad
	 * @return float
	 */
	public function getUnitVolume() {
		return ($this->getUnitWidth() * $this->getUnitHeight() * $this->getUnitLength() / 1000000);
	}

	/**
	 * Calcula el volumen en m3 segun la informacion ingresada en la cotizacion sobre el bulto
	 * @return float
	 */	
	public function getCartonVolume() {
		return ($this->getCartonWidth() * $this->getCartonHeight() * $this->getCartonLength() / 1000000);		
	}
	
	/**
	 * Calcula la densidad segun la informacion ingresada en la cotizacion sobre la unidad
	 */
	function getUnitDensity() {
		
		if ($this->getUnitVolume() == 0)
			return 0;
		
		return ($this->getUnitGrossWeigth() / $this->getUnitVolume());
	}
	
	/**
	 * Calcula la densidad segun la informacion ingresada en la cotizacion sobre la unidad
	 */
	function getCartonDensity() {

		if ($this->getCartonVolume() == 0)
			return 0;
		
		return ($this->getCartonGrossWeigth() / $this->getCartonVolume());

	}

	/**
	 * Calcula el volumen segun la informacion ingresada en la cotizacion sobre el bulto
	 * @return float
	 */	
	public function getTotalVolume() {
		return ($this->getUnitVolume() * $this->getQuantity());		
	}

	/**
	 * Calcula el volumen segun la informacion ingresada en la cotizacion sobre el bulto
	 * @return float
	 */	
	public function getTotalWeigth() {
		return ($this->getUnitGrossWeigth() * $this->getQuantity());		
	}


} // SupplierQuotationItem
