<?php

require_once 'import/classes/om/BaseSupplierQuotation.php';


/**
 * Skeleton subclass for representing a row from the 'import_supplierQuotation' table.
 *
 * Cotizacion de Proveedor
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:02:11 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class SupplierQuotation extends BaseSupplierQuotation {
	
	const STATUS_NEW = 1;
	const STATUS_WAITING_RESPONSE = 2;
	const STATUS_CONFIRMED = 3;
	
	private $statusNames = array(
								SupplierQuotation::STATUS_NEW => 'New',
								SupplierQuotation::STATUS_CONFIRMED => 'Confirmed'
							);	
	
	/**
	 * Devuelve el nombre del status actual de la cotizacion
	 * @return string
	 */
	public function getStatusName() {
		return $this->statusNames[$this->getStatus()];
	}
	
	/**
	 * Obtiene un cierto elemento de la cotizacion
	 * @param integer $id id del elemento a obtener
	 */
	public function getSupplierQuotationItem($id) {

		require_once('SupplierQuotationItemPeer.php');
		
		$criteria = new Criteria();
		$criteria->add(SupplierQuotationItemPeer::SUPPLIERQUOTATIONID,$this->getId());
		$criteria->add(SupplierQuotationItemPeer::ID,$id);
		
		$result = $this->getSupplierQuotationItems($criteria);
		return $result[0];
	}
	
	/**
	 * Crea un mensaje de notificacion a proveedor
	 * @param String $content Contenido del mensaje
	 * @param String $subject Asunto del mensaje
	 * @return Swift_Message
	 */
	private function createNotifyMessage($content,$subject = '') {

		require_once('EmailManagement.php');
		
		if (empty($subject)) {
			$subject = 'Notificacion de Creacion de Pedido de Cotizacion';
		}
		
		$manager = new EmailManagement();
		
		//creamos el mensaje multipart
		$message = $manager->createMultipartMessage($subject,$content);
		
		return $message;
	}
	
	/** 
	 * Envia un mensaje de notificacion
	 * @param String o Swift_RecipientList $destination destinatarios del email
	 * @param Swift_Message $message mensaje a enviar
	 * @return boolean
	 */
	private function sendMessage($destination,$message) {

		require_once('EmailManagement.php');

		$manager = new EmailManagement();

		global $system;
		$mailFrom = $system["config"]["system"]["parameters"]["fromEmail"];

		//realizamos el envio
		$result = $manager->sendMessage($destination,$mailFrom,$message);
		
		return $result;
	}
	
	/**
	 * Notifica a un proveedor de la existencia de un pedido de cotizacion
	 * 
	 * @param String $content Contenido del Email (debe ser generado de forma externa. Ver ImportBaseAction.php)
	 * @param String $subject Asunto del Email Opcional
	 *
	 */
	public function notifySupplier($content,$subject='') {
		
		//creamos el mensaje multipart
		$message = $this->createNotifyMessage($content,$subject);

		$supplier = $this->getSupplier();
		
		return $this->sendMessage($supplier->getEmail(),$message);
		
	}
	
	/**
	 * Notifica a un proveedor de la existencia de un pedido de cotizacion
	 * 
	 * @param String $content Contenido del Email (debe ser generado de forma externa. Ver ImportBaseAction.php)
	 * @param String $subject Asunto del Email Opcional
	 *
	 */
	public function notifyRecipients($emails,$content,$subject) {
	
		//creamos el mensaje multipart
		$message = $this->createNotifyMessage($content,$subject);

		require_once('EmailManagement.php');
		
		$manager = new EmailManagement();

		//creamos una lista de multiples recipientes
		$recipientList = $manager->createMultipleRecipientsList($emails);
		
		return $this->sendMessage($recipientList,$message);
		
	}
	
	
	/**
	 * Regenera el codigo de acceso para un supplier.
	 * @return boolean
	 */
	public function regenerateSupplierAccessToken() {
		
		try {
			$this->setSupplierAccessToken(SupplierQuotationPeer::generateRandomSupplierAccessCode());
			$this->save();
			
		} catch (PropelException $e) {
			return false;
		}
		
		return true;
	}
	
	/**
	 * Confirma una cotizacion de proveedor
	 * @return boolean
	 */
	public function confirm() {

		try {
			$this->setStatus(SupplierQuotation::STATUS_CONFIRMED);
			$this->save();			
		} catch (PropelException $e) {
			return false;
		}
		
		return true;
	}
	
	/**
	 * Indica si la cotizacion se encuentra confirmada
	 * @return boolean
	 */
	public function isConfirmed() {
		return ($this->getStatus() == SupplierQuotation::STATUS_CONFIRMED);
	}	
	

} // SupplierQuotation
