<?php

require_once 'import/classes/om/BaseSupplierQuotation.php';


/**
 * Skeleton subclass for representing a row from the 'import_supplierQuotation' table.
 *
 * Cotizacion de Proveedor
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:02:11 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class SupplierQuotation extends BaseSupplierQuotation {
	
	const STATUS_NEW = 1;
	const STATUS_WAITING_RESPONSE = 2;
	
	private $statusNames = array(
								ClientQuotation::STATUS_NEW => 'New'
							);	
	
	/**
	 * Devuelve el nombre del status actual de la cotizacion
	 * @return string
	 */
	public function getStatusName() {
		return $this->statusNames[$this->getStatus()];
	}
	
	/**
	 * Obtiene un cierto elemento de la cotizacion
	 * @param integer $id id del elemento a obtener
	 */
	public function getSupplierQuotationItem($id) {

		require_once('SupplierQuotationItemPeer.php');
		
		$criteria = new Criteria();
		$criteria->add(SupplierQuotationItemPeer::SUPPLIERQUOTATIONID,$this->getId());
		$criteria->add(SupplierQuotationItemPeer::ID,$id);
		
		$result = $this->getSupplierQuotationItems($criteria);
		return $result[0];
	}
	
	/**
	 * Notifica a un proveedor de la existencia de un pedido de cotizacion
	 * 
	 * @param String $content Contenido del Email (debe ser generado de forma externa. Ver ImportBaseAction.php)
	 * @param String $subject Asunto del Email Opcional
	 *
	 */
	public function notifySupplier($content,$subject) {
	
		require_once('EmailManagement.php');
		
		if (empty($subject)) {
			$subject = 'Notificacion de Creacion de Pedido de Cotizacion';
		}
		
		$manager = new EmailManagement();
		
		//creamos el mensaje multipart
		$message = $manager->createMultipartMessage($subject,$content);

		$supplier = $this->getSupplier();
		
		global $system;
		$mailFrom = $system["config"]["system"]["parameters"]["fromEmail"];

		//realizamos el envio
		$result = $manager->sendMessage($supplier->getEmail(),$mailFrom,$message);
		
		return $result;
		
	}
	

} // SupplierQuotation
