<?php

require_once 'import/classes/om/BaseSupplierPurchaseOrder.php';


/**
 * Skeleton subclass for representing a row from the 'import_supplierPurchaseOrder' table.
 *
 * Orden de Pedido a Proveedor
 *
 * This class was autogenerated by Propel on:
 *
 * Mon Feb  2 17:24:15 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class SupplierPurchaseOrder extends BaseSupplierPurchaseOrder {

} // SupplierPurchaseOrder
