DELETE FROM `multilang_text` WHERE `moduleName` = 'import' AND `languageId` = '1';
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('1', 'import', '1','Exportaciones');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('2', 'import', '1','Cotizaciones de Proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('3', 'import', '1','A continuación puede ver el listado de sus pedidos de cotización a proveedores y sus correspondientes estados.');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('4', 'import', '1','Para ver las solicitudes de cotización a un proveedor en particular, seleccione dicho proveedor de la lista');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('5', 'import', '1','Filtrar por proveedores');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('6', 'import', '1','Proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('7', 'import', '1','Seleccione un proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('8', 'import', '1','Aplicar Filtro');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('9', 'import', '1','Id');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('10', 'import', '1','Fecha');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('11', 'import', '1','Estado');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('12', 'import', '1','Completar');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('13', 'import', '1','Completar la solicitud con los datos suministrados por el proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('14', 'import', '1','Editar');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('15', 'import', '1','Editar Solicitud de Cotización');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('16', 'import', '1','Reenviar');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('17', 'import', '1','Reenviar a Destinatario Original');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('18', 'import', '1','Ver Historial');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('19', 'import', '1','Consultar histórico de solicitud');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('20', 'import', '1','Reenviar a otros destinatarios');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('21', 'import', '1','Enviar la solicitud a otros destinatarios');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('22', 'import', '1','Destinatarios (separados por coma):');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('23', 'import', '1','Eliminar');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('24', 'import', '1','Eliminar solicitud de cotización');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('25', 'import', '1','¿Está seguro que desea eliminar la cotización?');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('26', 'import', '1','Información General de la cotización de proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('27', 'import', '1','Código de acceso del Proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('28', 'import', '1','Solicitud de Cotización de Cliente Relacionada');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('29', 'import', '1','Productos a cotizar por el proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('30', 'import', '1','Código');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('31', 'import', '1','Nombre');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('32', 'import', '1','Plazo de Entrega');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('33', 'import', '1','Cantidad');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('34', 'import', '1','Precio Unitario del Proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('35', 'import', '1','Dias');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('36', 'import', '1','No se ha cotizado');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('37', 'import', '1','Negociar');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('38', 'import', '1','Se ha pedido la negociación del item y se ha notificado al proveedor.');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('39', 'import', '1','Solicitud de Cotización');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('40', 'import', '1','Cotización de Producto');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('41', 'import', '1','A continuación podrá ingresar los datos de la cotización del producto');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('42', 'import', '1','Para guardar el precio y confirmar la cotización del producto, haga click en &quot;Cotizar Item&quot;. Recuerde que puede modificar los datos del item mientras no haya confirmado la cotización completa.');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('43', 'import', '1','Detalle del producto');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('44', 'import', '1','Descripción');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('45', 'import', '1','Información de Empaque');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('46', 'import', '1','El producto se entrega en');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('47', 'import', '1','Empaques Unitarios');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('48', 'import', '1','Bultos');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('49', 'import', '1','Dimensiones Unidad:');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('50', 'import', '1','Alto');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('51', 'import', '1','Largo');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('52', 'import', '1','Ancho');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('53', 'import', '1','cm.');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('54', 'import', '1','Peso Bruto Unidad');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('55', 'import', '1','kg.');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('56', 'import', '1','Dimensiones Bulto');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('57', 'import', '1','Unidades por Bulto');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('58', 'import', '1','unidades');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('59', 'import', '1','Peso Bruto por bulto');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('60', 'import', '1','Precio unitario');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('61', 'import', '1','US$/u');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('62', 'import', '1','Entrega');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('63', 'import', '1','Comentarios');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('64', 'import', '1','Cotizar Item');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('65', 'import', '1','Cancelar');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('66', 'import', '1','Usuario');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('67', 'import', '1','Comentario');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('68', 'import', '1','Proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('69', 'import', '1','Historial de comentarios');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('70', 'import', '1','Agregar Comentario');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('71', 'import', '1','A continuación podrá agregar un comentario a esta cotización.');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('72', 'import', '1','Nueva');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('73', 'import', '1','Cotización solicitada');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('74', 'import', '1','Aceptada');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('75', 'import', '1','Esperando por precio');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('76', 'import', '1','Cotizada');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('77', 'import', '1','Cotizada parcialmente');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('78', 'import', '1','En negociación');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('79', 'import', '1','Estimado Proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('80', 'import', '1','Tenemos una solicitud de cotización. Para responderla, por favor haga click ');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('81', 'import', '1','Si el link de arriba no funciona pude ingresar copiando este link y pegarlo en el navegador');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('82', 'import', '1','aquí');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('83', 'import', '1','Solicitud de Cotización');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('84', 'import', '1','Agregando producto');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('85', 'import', '1','buscando');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('86', 'import', '1','procesando, cargando valores por default de incoterm y puerto para el proveedor');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('87', 'import', '1','eliminando producto');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('88', 'import', '1','cargando ordenes');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('89', 'import', '1','En proceso');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('90', 'import', '1','Fabricación solicitada');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('91', 'import', '1','En tiempo');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('92', 'import', '1','Retrasada');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('93', 'import', '1','Detenida');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('94', 'import', '1','Esperando transporte');
