DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Security%' and `language` = '';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityAffiliatesEdit', 'Editar permisos de usuarios', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityRegistrationEdit', '2', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityUsersEdit', '4', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionDoSave', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionDoSaveByAffiliate', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionList', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionListUsersByAffiliate', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionNoCheckLoginDoSave', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionNoCheckLoginList', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionRegUsersDoSave', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionRegUsersList', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleAffiliateUsersDoSave', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleAffiliateUsersList', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleDoSave', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleList', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleRegUsersDoSave', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleRegUsersList', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleUsersDoSave', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleUsersList', '', 'esp');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityNoPermission', '', 'esp');
