DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Security%' AND `language` = 'eng';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityAffiliatesEdit', 'Edit user by affiliate permissions', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityRegistrationEdit', 'Edit user by registration permissions', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityUsersEdit', 'Edit user permissions', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionListUsersByAffiliate', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityNoPermission', 'Detination of access without permission requestef', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleUsersList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionNoCheckLoginList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleUsersDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionRegUsersList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionNoCheckLoginDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleRegUsersDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleAffiliateUsersList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionRegUsersDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleRegUsersList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleAffiliateUsersDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionDoSaveByAffiliate', '', 'eng');
