DELETE FROM `multilang_text` WHERE `moduleName` = 'common' AND `languageId` = '2';
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('1', 'common', '2','Edit');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('2', 'common', '2','Delete');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('3', 'common', '2','Accept');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('4', 'common', '2','Search');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('5', 'common', '2','First');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('6', 'common', '2','Prev.');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('7', 'common', '2','Page');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('8', 'common', '2','of');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('9', 'common', '2','Next');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('10', 'common', '2','Last');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('11', 'common', '2','English');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('12', 'common', '2','Yes');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('13', 'common', '2','No');
