DELETE FROM `multilang_text` WHERE `moduleName` = 'common' AND `languageId` = '3';
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('1', 'common', '3','编辑');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('2', 'common', '3','删除');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('3', 'common', '3','接受');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('4', 'common', '3','搜索');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('5', 'common', '3','第');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('6', 'common', '3','前');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('7', 'common', '3','页');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('8', 'common', '3','的');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('9', 'common', '3','下');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('10', 'common', '3','最后');
INSERT INTO `multilang_text` ( `id` , `moduleName` , `languageId` , `text` ) VALUES ('11', 'common', '3','中文');
