<?php
// This file generated by Propel 1.3.0 convert-props target
// from XML runtime conf file /Users/ak/Work/Proyects/importaciones/WEB-INF/classes/propel/runtime-conf.xml
return array_merge_recursive(array (
  'log' => 
  array (
    'type' => 'file',
    'name' => 'e:\\temp\\propel.log',
    'ident' => 'anmaga',
    'level' => '7',
  ),
  'propel' => 
  array (
    'datasources' => 
    array (
      'anmaga' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'phptype' => 'mysql',
          'hostspec' => 'localhost',
          'database' => 'anmaga',
          'username' => 'root',
          'password' => 'dxukal',
        ),
      ),
      'mluse' => 
      array (
        'adapter' => 'mysql',
        'connection' => 
        array (
          'phptype' => 'mysql',
          'hostspec' => 'localhost',
          'database' => 'anmaga',
          'username' => 'root',
          'password' => 'dxukal',
        ),
      ),
      'default' => 'anmaga',
    ),
    'generator_version' => '1.3.0',
  ),
), include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'application-classmap.php'));