DELETE FROM `security_actionLabel` WHERE `action` LIKE 'Security%' and `language` = '';
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityAffiliatesEdit', 'Edit user', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityRegistrationEdit', '3', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityUsersEdit', '5', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionDoSaveByAffiliate', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionListUsersByAffiliate', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionNoCheckLoginDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionNoCheckLoginList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionRegUsersDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityActionRegUsersList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleAffiliateUsersDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleAffiliateUsersList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleRegUsersDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleRegUsersList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleUsersDoSave', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityModuleUsersList', '', 'eng');
INSERT INTO `security_actionLabel` ( `action` , `label` , `language` ) VALUES ('SecurityNoPermission', '', 'eng');
