<?php
/*
* Filename         : Main.php
* Application Name : MyAppl
* Application Desc : My Application Description
* Author name      : Joe J. Blogs
* Build Date       : 3-Oct-2006
* 
* //////////
* // This php.MVC source file was generated by SleeK Action Builder.
* // http://www.phpmvc.net/builder/
* /////////
*
* $Header$
* $Revision$
* $Date$
*
* Copyright (c) 2006 Joe J. Blogs. All rights reserved.
*/


// Usage: http://yourhost/PathTo/AppName/Main.php

// Set error reporting level. See PHP manual: XXVI. Error Handling and Logging Functions
// Note: E_STRICT  (PHP5 compliance) will cause the PHP4 code base to fail.
error_reporting(E_ALL ^ E_NOTICE);

// The application root directory
$appDir = NULL;
$appDir = dirname(__FILE__);

// Load the application bootup file
include ("$appDir/config/boot-php.inc.php");

?>