<?php

/**
 * Skeleton subclass for performing query and update operations on the 'affiliates_userInfo' table.
 *
 * Information about users by affiliates
 *
 * This class was autogenerated by Propel on:
 *
 * 07/18/07 19:06:41
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    anmaga
 */
class AffiliateUserInfoPeer extends BaseAffiliateUserInfoPeer {
  function getFromArray($params) {
    $obj = new AffiliateUserInfo();
    foreach ($params as $key => $value) {
      $setMethod = "set".$key;
      if ( method_exists($obj,$setMethod) ) {          
        if (!empty($value) || $value == "0")
          $obj->$setMethod($value);
        else
          $obj->$setMethod(null);
      }
    }   
    return $obj;
  }
} // AffiliateUserInfoPeer
